on: [push]

jobs:
  hello_world_job:
    runs-on: non-privileged-runner
    name: A job to test rootless docker available on ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: ls

      - uses: devecorsoft/install-rootless-docker@main

      - run: |
          whoami
          docker ps
